worker_processes auto;

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=1s;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server_tokens off;

    # Defines trusted addresses that are known to send correct replacement addresses.
    # set_real_ip_from 1.2.3.4;
    # real_ip_header X-Forwarded-For;
    # real_ip_recursive on;

    # Force security headers
    proxy_hide_header X-Frame-Options;
    proxy_hide_header X-Content-Type-Options;
    proxy_hide_header X-XSS-Protection;
    proxy_hide_header X-Robots-Tag;
    include headers/security.conf;

    # use the kernel sendfile
    sendfile on;

    # prepend http headers before sendfile()
    tcp_nopush on;

    keepalive_timeout 65;
    # maximum accepted body size of client request
    client_max_body_size 4G;
    tcp_nodelay on;

    gzip on;
    gzip_vary on;
    gzip_min_length 500;

    gzip_disable "MSIE [1-6]\.(?!.*SV1)";
    gzip_types text/plain text/xml text/css
        text/comma-separated-values
        text/javascript application/x-javascript
        application/atom+xml image/x-icon;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    proxy_redirect off;

    # set allowed hosts
    map $host $allowed_host {
        # allowed.example.com allowed.example.com;
        # default your.dam.host.com;
        default $host; # comment out when the above is enabled
    }

    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $allowed_host;
    proxy_set_header X-Forwarded-Host $allowed_host;

    # set cors origin
    map $http_origin $cors_origin {
        # allowed.example.com $http_origin;
        default "*";
    }

    # rate limiting
    # geo $limit {
    #     default 1;
    #     1.2.3.4 0;
    # }

    # map $limit $limit_key {
    #     0 "";
    #     1 $binary_remote_addr;
    # }

    # limit_req_zone $limit_key zone=main:10m rate=20r/s;
    # limit_req zone=main burst=50 nodelay;
    # limit_req_status 429;

    proxy_set_header X-Forwarded-Proto https;

    # ssl settings
    ssl_certificate      /etc/nginx/ssl/server.crt;
    ssl_certificate_key  /etc/nginx/ssl/server.key;

    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers on;

    upstream backend {
        zone backend_zone 64k;
        server backend:4001 resolve;
    }

    upstream streamer {
        zone streamer_zone 64k;
        server streamer:5000 resolve;
    }

    upstream anycable_go {
        zone anycable_go_zone 64k;
        server anycable_go:5004 resolve;
    }

    # http -> https redirect
    server {
        server_name _;
        listen 80;

        # Do not enforce SSL on localhost originated requests
        if ($host != 127.0.0.1) {
            rewrite ^(.*) https://$allowed_host$1 permanent;
        }

        include locations/*.conf;
    }

    # https
    server {
        server_name _;
        listen 443 default_server ssl;

        include locations/*.conf;

        proxy_send_timeout 120;
        proxy_read_timeout 120;
    }

}
